### PR TITLE
Fix index.js and message event

### PR DESCRIPTION
**Pull request by SomeNormalRando**
`eslint --fix`ed every single file and manually fixed index.js and message event (moved into a new file)

### CODE REVIEW

**Comment by SomeNormalRando** [comment]
I may have just undoed everything prettier

**Comment by thehairy** [comment]
Yeah, there is no way I'm gonna merge this.
Fix the eslint settings and I may merge it.

**Review by thehairy — CHANGES_REQUESTED** [review]
Fix eslint settings so it fits with prettier.

**Comment by thehairy** [comment]
Please make a PR to the testing branch.

**Pull request closed without merging**
